-- Insert categories
INSERT INTO livetv_categories (name) VALUES
('Documentarios'),('Entretenimento'),('Esportes'),('Filmes'),('Infantil'),('Internacionais'),('Noticias'),('Series'),('TV Aberta');

-- Insert channels using por_categoria (unique slugs only)
INSERT INTO livetv_channels (slug, name, category, stream_url, format, status) VALUES
('animal-planet','Animal Planet','Documentarios','https://canais.fazoeli.co.za/fontes/smart/animal-planet.m3u8','m3u8','offline'),
('discovery','Discovery Channel','Documentarios','https://canais.fazoeli.co.za/fontes/smart/discovery.m3u8','m3u8','offline'),
('discovery-hh','Discovery H&H','Documentarios','https://canais.fazoeli.co.za/fontes/smart/discovery-hh.m3u8','m3u8','offline'),
('discovery-science','Discovery Science','Documentarios','https://canais.fazoeli.co.za/fontes/smart/discovery-science.m3u8','m3u8','offline'),
('discovery-turbo','Discovery Turbo','Documentarios','https://canais.fazoeli.co.za/fontes/smart/discovery-turbo.m3u8','m3u8','offline'),
('discovery-world','Discovery World','Documentarios','https://canais.fazoeli.co.za/fontes/smart/discovery-world.m3u8','m3u8','offline'),
('food-network','Food Network','Documentarios','https://canais.fazoeli.co.za/fontes/smart/food-network.m3u8','m3u8','offline'),
('hgtv','HGTV','Documentarios','https://canais.fazoeli.co.za/fontes/smart/hgtv.m3u8','m3u8','online'),
('history','History','Documentarios','https://canais.fazoeli.co.za/fontes/smart/history.m3u8','m3u8','online'),
('history2','History 2','Documentarios','https://canais.fazoeli.co.za/fontes/smart/history2.m3u8','m3u8','online'),
('investigation-discovery','Investigation Discovery','Documentarios','https://canais.fazoeli.co.za/fontes/smart/investigation-discovery.m3u8','m3u8','offline'),
('tlc','TLC','Documentarios','https://canais.fazoeli.co.za/fontes/smart/tlc.m3u8','m3u8','online'),
('arte1','Arte 1','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/arte1.m3u8','m3u8','online'),
('bbb1','BBB CAN 1','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/bbb1.m3u8','m3u8','online'),
('bbb10','BBB CAN 10','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/bbb10.m3u8','m3u8','online'),
('bbb2','BBB CAN 2','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/bbb2.m3u8','m3u8','online'),
('bbb3','BBB CAN 3','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/bbb3.m3u8','m3u8','online'),
('bbb4','BBB CAN 4','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/bbb4.m3u8','m3u8','online'),
('bbb5','BBB CAN 5','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/bbb5.m3u8','m3u8','online'),
('bbb6','BBB CAN 6','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/bbb6.m3u8','m3u8','online'),
('bbb7','BBB CAN 7','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/bbb7.m3u8','m3u8','online'),
('bbb8','BBB CAN 8','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/bbb8.m3u8','m3u8','online'),
('bbb9','BBB CAN 9','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/bbb9.m3u8','m3u8','online'),
('bis','BIS','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/bis.m3u8','m3u8','online'),
('classique-tv','Classique TV','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/classique-tv.m3u8','m3u8','offline'),
('gnt','GNT','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/gnt.m3u8','m3u8','online'),
('gospel-movie-tv','Gospel Movie TV','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/gospel-movie-tv.m3u8','m3u8','offline'),
('loading','Loading','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/loading.m3u8','m3u8','offline'),
('multishow','Multishow','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/multishow.m3u8','m3u8','online'),
('mytime-movie','MyTime Movie','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/mytime-movie.m3u8','m3u8','offline'),
('off','OFF','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/off.m3u8','m3u8','online'),
('revry-brasil','Revry Brasil','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/revry-brasil.m3u8','m3u8','offline'),
('cultura','TV Cultura','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/cultura.m3u8','m3u8','online'),
('viva','Viva','Entretenimento','https://canais.fazoeli.co.za/fontes/smart/viva.m3u8','m3u8','online'),
('band-sports','Band Sports','Esportes','https://canais.fazoeli.co.za/fontes/smart/band-sports.m3u8','m3u8','offline'),
('canal-do-inter','Canal do Inter','Esportes','https://canais.fazoeli.co.za/fontes/smart/canal-do-inter.m3u8','m3u8','offline'),
('combate','Combate','Esportes','https://canais.fazoeli.co.za/fontes/smart/combate.m3u8','m3u8','online'),
('espn','ESPN','Esportes','https://canais.fazoeli.co.za/fontes/smart/espn.m3u8','m3u8','online'),
('espn2','ESPN 2','Esportes','https://canais.fazoeli.co.za/fontes/smart/espn2.m3u8','m3u8','online'),
('espn3','ESPN 3','Esportes','https://canais.fazoeli.co.za/fontes/smart/espn3.m3u8','m3u8','online'),
('espn4','ESPN 4','Esportes','https://canais.fazoeli.co.za/fontes/smart/espn4.m3u8','m3u8','online'),
('espn5','ESPN 5','Esportes','https://canais.fazoeli.co.za/fontes/smart/espn5.m3u8','m3u8','online'),
('fifa-plus','FIFA+ Português','Esportes','https://canais.fazoeli.co.za/fontes/smart/fifa-plus.m3u8','m3u8','offline'),
('premiere','Premiere','Esportes','https://canais.fazoeli.co.za/fontes/smart/premiere.m3u8','m3u8','online'),
('premiere2','Premiere 2','Esportes','https://canais.fazoeli.co.za/fontes/smart/premiere2.m3u8','m3u8','online'),
('premiere3','Premiere 3','Esportes','https://canais.fazoeli.co.za/fontes/smart/premiere3.m3u8','m3u8','online'),
('premiere4','Premiere 4','Esportes','https://canais.fazoeli.co.za/fontes/smart/premiere4.m3u8','m3u8','online'),
('sportv','SporTV','Esportes','https://canais.fazoeli.co.za/fontes/smart/sportv.m3u8','m3u8','online'),
('sportv2','SporTV 2','Esportes','https://canais.fazoeli.co.za/fontes/smart/sportv2.m3u8','m3u8','online'),
('sportv3','SporTV 3','Esportes','https://canais.fazoeli.co.za/fontes/smart/sportv3.m3u8','m3u8','online'),
('cinemax','Cinemax','Filmes','https://canais.fazoeli.co.za/fontes/smart/cinemax.m3u8','m3u8','online'),
('curta','Curta!','Filmes','https://canais.fazoeli.co.za/fontes/smart/curta.m3u8','m3u8','online'),
('hbo','HBO','Filmes','https://canais.fazoeli.co.za/fontes/smart/hbo.m3u8','m3u8','online'),
('hbo2','HBO 2','Filmes','https://canais.fazoeli.co.za/fontes/smart/hbo2.m3u8','m3u8','online'),
('hbo-family','HBO Family','Filmes','https://canais.fazoeli.co.za/fontes/smart/hbo-family.m3u8','m3u8','offline'),
('hbo-mundi','HBO Mundi','Filmes','https://canais.fazoeli.co.za/fontes/smart/hbo-mundi.m3u8','m3u8','offline'),
('hbo-plus','HBO Plus','Filmes','https://canais.fazoeli.co.za/fontes/smart/hbo-plus.m3u8','m3u8','offline'),
('hbo-pop','HBO Pop','Filmes','https://canais.fazoeli.co.za/fontes/smart/hbo-pop.m3u8','m3u8','offline'),
('hbo-xtreme','HBO Xtreme','Filmes','https://canais.fazoeli.co.za/fontes/smart/hbo-xtreme.m3u8','m3u8','offline'),
('megapix','Megapix','Filmes','https://canais.fazoeli.co.za/fontes/smart/megapix.m3u8','m3u8','online'),
('space','Space','Filmes','https://canais.fazoeli.co.za/fontes/smart/space.m3u8','m3u8','online'),
('studio-universal','Studio Universal','Filmes','https://canais.fazoeli.co.za/fontes/smart/studio-universal.m3u8','m3u8','offline'),
('tcm','TCM','Filmes','https://canais.fazoeli.co.za/fontes/smart/tcm.m3u8','m3u8','online'),
('telecine-action','Telecine Action','Filmes','https://canais.fazoeli.co.za/fontes/smart/telecine-action.m3u8','m3u8','offline'),
('telecine-cult','Telecine Cult','Filmes','https://canais.fazoeli.co.za/fontes/smart/telecine-cult.m3u8','m3u8','offline'),
('telecine-fun','Telecine Fun','Filmes','https://canais.fazoeli.co.za/fontes/smart/telecine-fun.m3u8','m3u8','offline'),
('telecine-pipoca','Telecine Pipoca','Filmes','https://canais.fazoeli.co.za/fontes/smart/telecine-pipoca.m3u8','m3u8','offline'),
('telecine-premium','Telecine Premium','Filmes','https://canais.fazoeli.co.za/fontes/smart/telecine-premium.m3u8','m3u8','offline'),
('telecine-touch','Telecine Touch','Filmes','https://canais.fazoeli.co.za/fontes/smart/telecine-touch.m3u8','m3u8','offline'),
('24h-dragon-ball','24h Dragon Ball','Infantil','https://canais.fazoeli.co.za/fontes/smart/24h-dragon-ball.m3u8','m3u8','offline'),
('24h-simpsons','24h Simpsons','Infantil','https://canais.fazoeli.co.za/fontes/smart/24h-simpsons.m3u8','m3u8','offline'),
('24h-todo-mundo','24h Todo Mundo Odeia o Chris','Infantil','https://canais.fazoeli.co.za/fontes/smart/24h-todo-mundo.m3u8','m3u8','offline'),
('adult-swim','Adult Swim','Infantil','https://canais.fazoeli.co.za/fontes/smart/adult-swim.m3u8','m3u8','offline'),
('cartoon-network','Cartoon Network','Infantil','https://canais.fazoeli.co.za/fontes/smart/cartoon-network.m3u8','m3u8','offline'),
('cartoonito','Cartoonito','Infantil','https://canais.fazoeli.co.za/fontes/smart/cartoonito.m3u8','m3u8','online'),
('discovery-kids','Discovery Kids','Infantil','https://canais.fazoeli.co.za/fontes/smart/discovery-kids.m3u8','m3u8','offline'),
('geekdot','Geekdot','Infantil','https://canais.fazoeli.co.za/fontes/smart/geekdot.m3u8','m3u8','offline'),
('gloob','Gloob','Infantil','https://canais.fazoeli.co.za/fontes/smart/gloob.m3u8','m3u8','online'),
('gospel-cartoon','Gospel Cartoon','Infantil','https://canais.fazoeli.co.za/fontes/smart/gospel-cartoon.m3u8','m3u8','offline'),
('nickelodeon','Nickelodeon','Infantil','https://canais.fazoeli.co.za/fontes/smart/nickelodeon.m3u8','m3u8','online'),
('4k-travel-tv','4K Travel TV','Internacionais','https://canais.fazoeli.co.za/fontes/smart/4k-travel-tv.m3u8','m3u8','offline'),
('abc-news','ABC News','Internacionais','https://canais.fazoeli.co.za/fontes/smart/abc-news.m3u8','m3u8','offline'),
('accuweather','AccuWeather','Internacionais','https://canais.fazoeli.co.za/fontes/smart/accuweather.m3u8','m3u8','offline'),
('al-jazeera','Al Jazeera English','Internacionais','https://canais.fazoeli.co.za/fontes/smart/al-jazeera.m3u8','m3u8','offline'),
('angel-tv','Angel TV','Internacionais','https://canais.fazoeli.co.za/fontes/smart/angel-tv.m3u8','m3u8','offline'),
('bloomberg','Bloomberg','Internacionais','https://canais.fazoeli.co.za/fontes/smart/bloomberg.m3u8','m3u8','offline'),
('cbs-news','CBS News New York','Internacionais','https://canais.fazoeli.co.za/fontes/smart/cbs-news.m3u8','m3u8','offline'),
('cgtn','CGTN','Internacionais','https://canais.fazoeli.co.za/fontes/smart/cgtn.m3u8','m3u8','offline'),
('dazn-combat','DAZN Combat','Internacionais','https://canais.fazoeli.co.za/fontes/smart/dazn-combat.m3u8','m3u8','offline'),
('destination-tv','Destination TV','Internacionais','https://canais.fazoeli.co.za/fontes/smart/destination-tv.m3u8','m3u8','offline'),
('dw','DW English','Internacionais','https://canais.fazoeli.co.za/fontes/smart/dw.m3u8','m3u8','offline'),
('epix','Epix','Internacionais','https://canais.fazoeli.co.za/fontes/smart/epix.m3u8','m3u8','offline'),
('euronews','Euronews English','Internacionais','https://canais.fazoeli.co.za/fontes/smart/euronews.m3u8','m3u8','offline'),
('fox-sports','Fox Sports','Internacionais','https://canais.fazoeli.co.za/fontes/smart/fox-sports.m3u8','m3u8','offline'),
('kuriakos-kids','Kuriakos Kids','Internacionais','https://canais.fazoeli.co.za/fontes/smart/kuriakos-kids.m3u8','m3u8','offline'),
('lifetime-movies','Lifetime Movies','Internacionais','https://canais.fazoeli.co.za/fontes/smart/lifetime-movies.m3u8','m3u8','offline'),
('nat-geo-wild','Nat Geo Wild','Internacionais','https://canais.fazoeli.co.za/fontes/smart/nat-geo-wild.m3u8','m3u8','offline'),
('nat-geo','National Geographic','Internacionais','https://canais.fazoeli.co.za/fontes/smart/nat-geo.m3u8','m3u8','offline'),
('red-bull-tv','Red Bull TV','Internacionais','https://canais.fazoeli.co.za/fontes/smart/red-bull-tv.m3u8','m3u8','offline'),
('rt-documentary','RT Documentary','Internacionais','https://canais.fazoeli.co.za/fontes/smart/rt-documentary.m3u8','m3u8','offline'),
('the-movie-channel','The Movie Channel','Internacionais','https://canais.fazoeli.co.za/fontes/smart/the-movie-channel.m3u8','m3u8','offline'),
('band-news','Band News','Noticias','https://canais.fazoeli.co.za/fontes/smart/band-news.m3u8','m3u8','offline'),
('cnn-brasil','CNN Brasil','Noticias','https://canais.fazoeli.co.za/fontes/smart/cnn-brasil.m3u8','m3u8','offline'),
('globo-news','Globo News','Noticias','https://canais.fazoeli.co.za/fontes/smart/globo-news.m3u8','m3u8','offline'),
('jovem-pan-news','Jovem Pan News','Noticias','https://canais.fazoeli.co.za/fontes/smart/jovem-pan-news.m3u8','m3u8','offline'),
('record-news','Record News','Noticias','https://canais.fazoeli.co.za/fontes/smart/record-news.m3u8','m3u8','offline'),
('stz-tv','STZ TV','Noticias','https://canais.fazoeli.co.za/fontes/smart/stz-tv.m3u8','m3u8','offline'),
('ae','A&E','Series','https://canais.fazoeli.co.za/fontes/smart/ae.m3u8','m3u8','online'),
('amc','AMC','Series','https://canais.fazoeli.co.za/fontes/smart/amc.m3u8','m3u8','online'),
('axn','AXN','Series','https://canais.fazoeli.co.za/fontes/smart/axn.m3u8','m3u8','online'),
('sony','Sony Channel','Series','https://canais.fazoeli.co.za/fontes/smart/sony.m3u8','m3u8','offline'),
('tnt','TNT','Series','https://canais.fazoeli.co.za/fontes/smart/tnt.m3u8','m3u8','online'),
('tnt-novelas','TNT Novelas','Series','https://canais.fazoeli.co.za/fontes/smart/tnt-novelas.m3u8','m3u8','offline'),
('tnt-series','TNT Series','Series','https://canais.fazoeli.co.za/fontes/smart/tnt-series.m3u8','m3u8','offline'),
('universal-tv','Universal TV','Series','https://canais.fazoeli.co.za/fontes/smart/universal-tv.m3u8','m3u8','offline'),
('warner','Warner Channel','Series','https://canais.fazoeli.co.za/fontes/smart/warner.m3u8','m3u8','offline'),
('amazon-sat','Amazon Sat','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/amazon-sat.m3u8','m3u8','offline'),
('band','Band','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/band.m3u8','m3u8','online'),
('cwb-tv','CWB TV','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/cwb-tv.m3u8','m3u8','offline'),
('despertar-tv','Despertar TV','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/despertar-tv.m3u8','m3u8','offline'),
('globo-am','Globo AM','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/globo-am.m3u8','m3u8','offline'),
('globo-es','Globo ES','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/globo-es.m3u8','m3u8','offline'),
('globo-mg','Globo MG','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/globo-mg.m3u8','m3u8','offline'),
('globo-rj','Globo RJ','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/globo-rj.m3u8','m3u8','offline'),
('globo-rs','Globo RS','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/globo-rs.m3u8','m3u8','offline'),
('globo-sp','Globo SP','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/globo-sp.m3u8','m3u8','offline'),
('impd','IMPD','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/impd.m3u8','m3u8','offline'),
('record-internacional','Record Internacional','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/record-internacional.m3u8','m3u8','offline'),
('record','Record TV','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/record.m3u8','m3u8','online'),
('rede-gospel','Rede Gospel','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/rede-gospel.m3u8','m3u8','offline'),
('rede-tv','RedeTV!','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/rede-tv.m3u8','m3u8','offline'),
('sbt','SBT','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/sbt.m3u8','m3u8','online'),
('sbt-interior','SBT Interior','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/sbt-interior.m3u8','m3u8','offline'),
('sertao-tv','Sertão TV','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/sertao-tv.m3u8','m3u8','offline'),
('aparecida','TV Aparecida','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/aparecida.m3u8','m3u8','online'),
('tv-brasil','TV Brasil','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/tv-brasil.m3u8','m3u8','offline'),
('tv-gazeta','TV Gazeta','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/tv-gazeta.m3u8','m3u8','offline'),
('tv-novo-tempo','TV Novo Tempo','TV Aberta','https://canais.fazoeli.co.za/fontes/smart/tv-novo-tempo.m3u8','m3u8','offline');